### ISSUE TITLE
Cannot load external assembly

### ISSUE THREAD

**Issue by johnkors** [scriptcs/scriptcs-sublime#15]
Maybe this is more of a Roslyn than a ScriptCs-Sublime question, but trying here for help anyhow. Given the following csx, referring to an external assembly with a given namespace and Person class :

``` csharp
#r "MyExternalTestAssembly.dll"

using System;
using MyExternalTestAssemblyNamespace;


var person = new Person();
for(int i =1; i < 6; i++)
{
    var person = new Person();
    var spoken = person.Speak();
    Console.WriteLine(spoken);
}
```

When I try to build with the Sublime ScriptCs build, I get

```
(1,1): error CS0006: Metadata file 'MyExternalTestAssembly.dll' could not be found
[Finished in 0.4s with exit code -1]
```

I've tried to put the dll into the packages folder as well, but that does not seem to help neither. What path does it use for looking up references?

**Comment by filipw** [comment]
Did you put in the `/bin` folder (relative to the script location)?

**Comment by johnkors** [comment]
Thanks,  @filipw ! Works now. Thanks.

Just out of curiosity - is that bin-folder a result of scriptcs or a Roslyn csx (rcsi.exe) ?

**Comment by filipw** [comment]
It's a bug in Roslyn - it requires all DLLs have to be in one place - that's why copy the relevant DLLs from the `packages` to `bin` too. And if you want to use your own custom DLL it has to go there too, or has to come from GAC.

We have a separate bug for that already, so I will close this one.
