### ISSUE TITLE
Arg to auto close REPL after running script

### ISSUE THREAD

**Issue by jameshulse** [scriptcs/scriptcs-sublime#25]
When running a script via `scriptcs {file} -repl` it would be nice to be able to pass another argument such as `-autoclose` which automatically exits scriptcs once it has completed running the file. It would also be handy to be able to mute the extra output such as "INFO: Loading preseeded script:" etc.

This would be useful for the sublime text plugin to allow for running simple scripts without having to use `Console.WriteLine` for output - we would benefit from the repl auto-dumping.

I'll see if I can get a pull request going which has a rough outline of what I want to achieve.

**Comment by filipw** [comment]
The extra output can be switched to DEBUG that's no problem. As far as autoexit, that's fine too I think, although I still am having hard time of imagining the use case for that. script loaded into REPL isn't executed line by line but as if it was a single line - so I don't think the auto dumping would not work as you imagine.

With that said, maybe there's some value in executing external scripts in REPL line by line.

Anyway, this issue really belongs into the core not in this project. Can you re-open there?

**Comment by jameshulse** [comment]
Ah sorry, I think I wanted to submit to that repo and ended up here. I've moved it now: https://github.com/scriptcs/scriptcs/issues/482.

The use case is simply using sublime text as the editor for a single line statement. When in the command line I don't get nice editing capabilities like simply clicking in the middle of a line to make a change.
