### ISSUE TITLE
Submit package to Sublime Text Package Control Channel

### ISSUE THREAD

**Issue by follesoe** [scriptcs/scriptcs-sublime#4]
Sublime Text Package Manager is an convenient way to install Sublime Packages. To submit a new package all you have to do is add a new entry to `repositories.json`. See http://wbond.net/sublime_packages/package_control/package_developers#Submitting_a_Package for more information.

**Comment by follesoe** [comment]
I have submitted a pull request on the package_control_channel, adding the scriptcs/scriptcs-sublime repo to the list of packages.

The pull request can be found at https://github.com/wbond/package_control_channel/pull/1139

Once it is merged, one should be able to install the package via the package manager. Once we do that, it would be smart to have a similar workflor as the scriptcs repo (a dev branch and a master branch). The Sublime package manager will simply pull master for updates, so if we push any unfinished features to master, users of the plugin will have those changes pulled down.

**Comment by tillig** [comment]
I was just able to install via Package Control so I think this can be closed.

**Comment by glennblock** [comment]
Yeah this was fixed AGES ago.

**Comment by glennblock** [comment]
@tillig have fun :-)
